name: snap-python-api # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Python Flask API packed as Snap # 79 char long summary
description: |
  Python Flask API packed as Snap

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps: 
  hello-api: 
    command: bin/flask-wrapper
    daemon: simple
    restart-condition: always
    plugs: [network-bind]
    environment:
      FLASK_APP: hello/hello

parts: 
  python-packages: 
    plugin: python
    source: .
    python-requirements: ['requirements.txt']

  flask-app:
    plugin: dump
    source: ./hello
    organize:
      hello.py: bin/
      flask-wrapper: bin/
      
